#
# Copyright (C) 2017-2025 Institute of Communication and Computer Systems (imu.iccs.gr)
#
# This Source Code Form is subject to the terms of the Mozilla Public License, v2.0, unless
# Esper library is used, in which case it is subject to the terms of General Public License v2.0.
# If a copy of the MPL was not distributed with this file, you can obtain one at
# https://www.mozilla.org/en-US/MPL/2.0/
#

apiVersion: v1
kind: Service
metadata:
  name: {{ include "nebulous-monitoring.fullname" . }}-public
  labels:
    {{- include "nebulous-monitoring.labels" . | nindent 4 }}-public
spec:
  type: NodePort
  ports:
    {{- range .Values.ports }}
    {{- if .public }}
    - name: {{ .name }}
      port: {{ .containerPort }}
      targetPort: {{ .containerPort }}
      nodePort: {{ .nodePort }}
      protocol: {{ .protocol }}
    {{- end }}
    {{- end }}
  selector:
    {{- include "nebulous-monitoring.selectorLabels" . | nindent 4 }}-public
