- project:
    check:
      jobs:
        - opendev-buildset-registry
        - nebulous-monitoring-helm-lint
        - nebulous-monitoring-build-container-images
        - nebulous-monitoring-hadolint
        - nebulous-platform-apply-helm-charts:
            dependencies:
              - name: nebulous-monitoring-build-container-images
                soft: true
        - nox-linters
    gate:
      jobs:
        - opendev-buildset-registry
        - nebulous-monitoring-helm-lint
        - nebulous-monitoring-upload-container-images
        - nebulous-monitoring-hadolint
        - nebulous-platform-apply-helm-charts:
            dependencies:
              - name: nebulous-monitoring-upload-container-images
                soft: true
        - nox-linters
    promote:
      jobs:
        - nebulous-monitoring-promote-container-images
