- project:
    check:
      jobs:
        - opendev-buildset-registry
        - nebulous-monitoring-helm-lint
        - nebulous-monitoring-build-container-images
        - nebulous-monitoring-hadolint
        - nebulous-platform-apply-helm-charts
        - nox-linters
    gate:
      jobs:
        - opendev-buildset-registry
        - nebulous-monitoring-helm-lint
        - nebulous-monitoring-upload-container-images
        - nebulous-monitoring-hadolint
        - nebulous-platform-apply-helm-charts
        - nox-linters
    promote:
      jobs:
        - nebulous-monitoring-promote-container-images
