name: CI
on:
  push:
    branches:
      - main
      - r[1-9]
  pull_request:
    branches:
      - main
      - r[1-9]
jobs:
#  build-and-push-ems-server:
#    name: Build and push EMS server
#    uses: eu-nebulous/github-actions/.github/workflows/build-and-push-container-image.yml@main
#    with:
#      context: nebulous
#      image-name: monitoring
#      target: ems-server-nebulous
#      tags: quay.io/nebulous/ems-server:latest
#    secrets: inherit

  build-and-push-ems-server-container-image:
    name: Build and push EMS server container image
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3.0.0

      - name: Log into quay.io
        if: github.event_name != 'pull_request'
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}

      - name: Set timestamp
        id: timestamp
        run: echo "timestamp=$(date +%Y%m%d%H%M%S)" >> "$GITHUB_OUTPUT"

      - name: Set tag-friendly ref name
        id: tagfriendly-ref
        run: echo "ref_name=$(echo '${{ github.ref_name }}' | sed 's|/|-|g')" >> "$GITHUB_OUTPUT"

      - name: Build and push container image
        id: build-and-push-container-image
        uses: docker/build-push-action@0565240e2d4ab88bba5387d719585280857ece09 # v5.0.0
        with:
          context: nebulous
          push: ${{ github.event_name != 'pull_request' }}
          target: ems-server-nebulous
          tags: |
            quay.io/nebulous/ems-server:latest
            quay.io/nebulous/monitoring:latest
            quay.io/nebulous/monitoring:${{ steps.tagfriendly-ref.outputs.ref_name }}
            quay.io/nebulous/monitoring:${{ github.sha }}
            quay.io/nebulous/monitoring:${{ steps.tagfriendly-ref.outputs.ref_name }}-${{ github.sha }}
            quay.io/nebulous/monitoring:${{ steps.tagfriendly-ref.outputs.ref_name }}-${{ github.sha }}-${{ steps.timestamp.outputs.timestamp }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

#  build-and-push-ems-client:
#    name: Build and push EMS client
#    uses: eu-nebulous/github-actions/.github/workflows/build-and-push-container-image.yml@main
#    with:
#      context: nebulous
#      image-name: monitoring
#      target: ems-client
#    secrets: inherit
