name: CI
on:
  push:
    branches:
      - main
      - r[1-9]
  pull_request:
    branches:
      - main
      - r[1-9]
jobs:
  build-and-push-monitoring:
    name: Build and push monitoring
    uses: eu-nebulous/github-actions/.github/workflows/build-and-push-container-image.yml@main
    with:
      context: nebulous
      image-name: monitoring
    secrets: inherit
