name: CI
on:
  push:
    branches:
      - main
      - r[1-9]
  pull_request:
    branches:
      - main
      - r[1-9]
  workflow_call:
    secrets:
      QUAY_USERNAME:
        required: false
      QUAY_PASSWORD:
        required: false

jobs:
#  build-and-push-monitoring:
#    name: Build and push monitoring
#    uses: eu-nebulous/github-actions/.github/workflows/build-and-push-container-image.yml@main
#    with:
#      context: nebulous
#      image-name: monitoring
#    secrets: inherit

  new-build-and-push-monitoring:
    name: New Build and push monitoring
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3.0.0

      - name: Log into quay.io
        if: github.event_name != 'pull_request'
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}

      - name: Set timestamp
        id: timestamp
        run: echo "timestamp=$(date +%Y%m%d%H%M%S)" >> "$GITHUB_OUTPUT"

      - name: Set tag-friendly ref name
        id: tagfriendly-ref
        run: echo "ref_name=$(echo '${{ github.ref_name }}' | sed 's|/|-|g')" >> "$GITHUB_OUTPUT"

      - name: Set docker properties
        id: set-docker-properties
        run: |
          echo "# Generated on: $(date -Iseconds)" > nebulous/docker-image.properties
          echo "docker.image.name=quay.io/nebulous/monitoring" >> nebulous/docker-image.properties
          echo "docker.image.tag=ems-server-${{ steps.tagfriendly-ref.outputs.ref_name }}" >> nebulous/docker-image.properties
          echo "docker.user=emsuser" >> nebulous/docker-image.properties
          echo "docker.user.home=/opt/ems-server" >> nebulous/docker-image.properties

      - name: Copy docker properties
        id: copy-docker-properties
        run: |
          cp nebulous/docker-image.properties nebulous/ems-core/
          cp nebulous/docker-image.properties nebulous/ems-nebulous/
          cat nebulous/docker-image.properties

      - name: Build and push EMS server container image
        id: build-and-push-ems-server-container-image
        uses: docker/build-push-action@0565240e2d4ab88bba5387d719585280857ece09 # v5.0.0
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            quay.io/nebulous/monitoring:${{ steps.tagfriendly-ref.outputs.ref_name }}
            quay.io/nebulous/monitoring:${{ github.sha }}
            quay.io/nebulous/monitoring:${{ steps.tagfriendly-ref.outputs.ref_name }}-${{ github.sha }}
            quay.io/nebulous/monitoring:${{ steps.tagfriendly-ref.outputs.ref_name }}-${{ github.sha }}-${{ steps.timestamp.outputs.timestamp }}
          file: nebulous/Dockerfile
          build-args: BUILDKIT_CONTEXT_KEEP_GIT_DIR=1
          target: ems-server-nebulous
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push EMS client container image
        id: build-and-push-ems-client-container-image
        uses: docker/build-push-action@0565240e2d4ab88bba5387d719585280857ece09 # v5.0.0
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            quay.io/nebulous/monitoring:ems-client-${{ steps.tagfriendly-ref.outputs.ref_name }}
            quay.io/nebulous/monitoring:ems-client-${{ github.sha }}
            quay.io/nebulous/monitoring:ems-client-${{ steps.tagfriendly-ref.outputs.ref_name }}-${{ github.sha }}
            quay.io/nebulous/monitoring:ems-client-${{ steps.tagfriendly-ref.outputs.ref_name }}-${{ github.sha }}-${{ steps.timestamp.outputs.timestamp }}
          file: nebulous/Dockerfile
          build-args: BUILDKIT_CONTEXT_KEEP_GIT_DIR=1
          target: ems-client
          cache-from: type=gha
          cache-to: type=gha,mode=max
